In [15]:
import pandas as pd

In [16]:
df = pd.read_csv("../data/raw/water_potability.csv")

In [17]:
df.sample(5)

,ph,Hardness,Solids,Chloramines,Sulfate,Conductivity,Organic_carbon,Trihalomethanes,Turbidity,Potability
1705,5.588130,220.817522,8730.312436,8.321897,300.220428,412.708557,6.478626,80.637806,3.165618,0
1274,5.548125,217.018259,34006.768745,6.647425,331.402947,430.269664,15.647036,64.980642,4.599236,0
2968,4.663492,170.951830,41452.625574,8.725765,362.415419,378.149000,16.274051,60.618754,3.742293,0
2173,NaN,204.258263,26321.689195,5.937496,NaN,487.273628,20.407809,70.340601,3.305588,0
1179,5.470802,213.160478,18295.370921,6.043395,NaN,317.948459,13.789267,49.642451,2.962852,1

In [18]:
df.columns = df.columns.str.lower()
df.sample(5)

,ph,hardness,solids,chloramines,sulfate,conductivity,organic_carbon,trihalomethanes,turbidity,potability
120,6.877457,136.879214,27433.587294,7.091522,307.397088,342.196347,18.403846,81.193412,3.827650,0
1434,7.322502,196.104298,19534.421648,6.661157,297.841381,418.075511,17.161768,69.467359,2.981649,0
914,5.791154,190.431679,20288.235569,6.298366,347.041020,544.857481,17.706838,84.388191,4.104835,0
1686,7.025457,184.484427,31659.962745,5.232020,NaN,559.002854,14.393046,56.290252,2.927051,0
2879,4.227537,201.447487,13122.329581,6.932558,374.843538,402.660774,22.823293,76.469426,4.479628,0

In [19]:
df.isnull().sum()

ph                 491
hardness             0
solids               0
chloramines          0
sulfate            781
conductivity         0
organic_carbon       0
trihalomethanes    162
turbidity            0
potability           0
dtype: int64

In [20]:
df.duplicated().sum()

np.int64(0)

In [21]:
df.dtypes

ph                 float64
hardness           float64
solids             float64
chloramines        float64
sulfate            float64
conductivity       float64
organic_carbon     float64
trihalomethanes    float64
turbidity          float64
potability           int64
dtype: object

In [22]:
df.describe()

,ph,hardness,solids,chloramines,sulfate,conductivity,organic_carbon,trihalomethanes,turbidity,potability
count,2785.000000,3276.000000,3276.000000,3276.000000,2495.000000,3276.000000,3276.000000,3114.000000,3276.000000,3276.000000
mean,7.080795,196.369496,22014.092526,7.122277,333.775777,426.205111,14.284970,66.396293,3.966786,0.390110
std,1.594320,32.879761,8768.570828,1.583085,41.416840,80.824064,3.308162,16.175008,0.780382,0.487849
min,0.000000,47.432000,320.942611,0.352000,129.000000,181.483754,2.200000,0.738000,1.450000,0.000000
25%,6.093092,176.850538,15666.690297,6.127421,307.699498,365.734414,12.065801,55.844536,3.439711,0.000000
50%,7.036752,196.967627,20927.833607,7.130299,333.073546,421.884968,14.218338,66.622485,3.955028,0.000000
75%,8.062066,216.667456,27332.762127,8.114887,359.950170,481.792304,16.557652,77.337473,4.500320,1.000000
max,14.000000,323.124000,61227.196008,13.127000,481.030642,753.342620,28.300000,124.000000,6.739000,1.000000

In [23]:
df.drop(columns="potability").eq(0).sum()

ph                 1
hardness           0
solids             0
chloramines        0
sulfate            0
conductivity       0
organic_carbon     0
trihalomethanes    0
turbidity          0
dtype: int64

In [24]:
df.to_csv("../data/processed/water_potability_cleaned.csv", index=False)